# docker-compose.yml (place at project root AJIO/)
services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017" # optional to expose DB to host; remove in production if you want DB private
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: ajio-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://admin:qwerty@mongo:27017/ajio?authSource=admin"
      PORT: 5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # build-time variable - will be embedded into Vite build as import.meta.env.VITE_API_BASE_URL
        VITE_API_BASE_URL: "http://backend:5000/api"
    container_name: ajio-frontend
    restart: always
    ports:
      - "3000:80" # visit http://<EC2_IP>:3000 for the UI
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

volumes:
  mongo_data:
