# docker-compose.yml (project root AJIO/)
services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: ajio-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    environment:
      # override MONGO_URI so backend authenticates to mongo container
      MONGO_URI: "mongodb://admin:qwerty@mongo:27017/ajio?authSource=admin"
      PORT: 5000 # ✅ moved inside backend.environment

volumes:
  mongo_data:
